"use client";

import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { createVehicle, getCurrentUser, getLookup, getVehiclesPage, logout, updateVehicle, type AuthenticatedUser, type LookupRecord, type VehiclePayload, type VehicleRecord } from "@/lib/api";
import { FleetSidebar } from "@/components/fleet-sidebar";

type Option = { id: number; label: string; parentId?: number };
type Lookups = Record<string, Option[]>;
const glyph: Record<string, string> = { dashboard: "⊞", group: "♙", directions_car: "◆", payments: "¤", description: "▤", storefront: "⌂", notifications: "●", logout: "⇥", add: "+", visibility: "◉", edit: "✎", delete: "×", close: "×", save: "✓", person_add: "⊕", settings: "⚙", sensors: "◌", menu_open: "≪", filter: "⌕" };
function Icon({ name }: { name: string }) { return <span aria-hidden className="cu-icon">{glyph[name] ?? "•"}</span>; }
function optionRows(rows: LookupRecord[], idKey: string, labelKeys: string[], parentKey?: string): Option[] { return rows.map((row) => { const id = row[idKey]; const label = labelKeys.map((key) => row[key]).find((value) => typeof value === "string"); const parent = parentKey ? row[parentKey] : undefined; return { id: typeof id === "number" ? id : 0, label: String(label ?? `ID ${id ?? "—"}`), parentId: typeof parent === "number" ? parent : undefined }; }).filter((item) => item.id > 0); }
function label(options: Option[] | undefined, id: number | null | undefined, fallback = "—") { return options?.find((item) => item.id === id)?.label ?? (id ? `Legacy ID ${id}` : fallback); }
function dateInput(value: string | null | undefined) { return value ? value.slice(0, 10) : ""; }
function dateDisplay(value: string | null | undefined) { return value ? new Date(value).toLocaleDateString("en-GB", { day: "2-digit", month: "short", year: "numeric" }) : "—"; }
function toDate(value: FormDataEntryValue | null) { const text = String(value ?? ""); return text ? `${text}T00:00:00` : null; }
function num(values: FormData, name: string, optional = false): number { const value = String(values.get(name) ?? ""); return (!value && optional ? null : Number(value)) as number; }

export default function VehiclesPage() {
  const router = useRouter();
  const [user, setUser] = useState<AuthenticatedUser | null>(null); const [checking, setChecking] = useState(true);
  const [records, setRecords] = useState<VehicleRecord[]>([]); const [total, setTotal] = useState(0); const [offset, setOffset] = useState(0); const pageSize = 10;
  const [search, setSearch] = useState({ q: "", plateNo: "", fleetNo: "" }); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const [lookups, setLookups] = useState<Lookups>({}); const [drawer, setDrawer] = useState<"create" | "view" | "edit" | null>(null); const [selected, setSelected] = useState<VehicleRecord | null>(null);
  const totalPages = Math.max(1, Math.ceil(total / pageSize)); const currentPage = Math.floor(offset / pageSize) + 1;
  const pageNumbers = useMemo(() => { const first = Math.max(1, Math.min(currentPage - 2, totalPages - 4)); return Array.from({ length: Math.min(5, totalPages) }, (_, index) => first + index); }, [currentPage, totalPages]);

  async function loadPage(nextOffset = 0, filters = search) { setLoading(true); setError(null); try { const page = await getVehiclesPage(nextOffset, pageSize, filters); setRecords(page.items); setTotal(page.total); setOffset(page.offset); } catch (cause) { setError(cause instanceof Error ? cause.message : "Vehicle records could not be loaded."); } finally { setLoading(false); } }
  useEffect(() => { async function initialise() { try { const activeUser = await getCurrentUser(); setUser(activeUser); await Promise.all([loadPage(0), loadLookups(setLookups)]); } catch (cause) { if (cause instanceof Error && cause.message.includes("session")) router.replace("/login"); else setError(cause instanceof Error ? cause.message : "FleetTrack could not be loaded."); } finally { setChecking(false); setLoading(false); } } void initialise(); }, [router]);
  async function signOut() { try { await logout(); } finally { router.replace("/login"); } }
  if (checking) return <main className="ft-loading">Loading FleetTrack vehicles…</main>; if (!user) return null;
  return <div className="cu-app"><FleetSidebar /><div className="cu-frame"><header className="cu-topbar"><div className="cu-crumb"><b>FleetTrack</b><span>/</span><span>Operations</span><span>/</span><strong>Vehicles</strong></div><div className="cu-user"><button type="button"><Icon name="storefront" /></button><button className="cu-notice" type="button"><Icon name="notifications" /></button><i /><span className="cu-avatar">{user.displayName.slice(0, 2).toUpperCase()}</span><span><b>{user.displayName}</b><small>{user.userName}</small></span><button className="cu-logout" onClick={signOut} type="button"><Icon name="logout" />Logout</button></div></header>
    <main className="cu-main"><div className="cu-page-heading"><div><h1>Vehicles</h1><p>Manage vehicle identity, registration, insurance, and operational master data.</p></div><button className="cu-primary" onClick={() => { setSelected(null); setDrawer("create"); }} type="button"><Icon name="add" />Add Vehicle</button></div>
      <section className="cu-filter-panel vh-filter"><div><label>General Search</label><input value={search.q} onChange={(event) => setSearch({ ...search, q: event.target.value })} placeholder="Plate, fleet, chassis, engine…" /></div><div><label>Plate Number</label><input value={search.plateNo} onChange={(event) => setSearch({ ...search, plateNo: event.target.value })} placeholder="Search plate…" /></div><div><label>Fleet Number</label><input value={search.fleetNo} onChange={(event) => setSearch({ ...search, fleetNo: event.target.value })} placeholder="Search fleet number…" /></div><button className="cu-filter-button" onClick={() => loadPage(0)} type="button"><Icon name="filter" />Search</button><button className="cu-clear" onClick={() => { const blank = { q: "", plateNo: "", fleetNo: "" }; setSearch(blank); void loadPage(0, blank); }} type="button">Clear</button></section>
      <div className="cu-list-meta"><span>{loading ? "Loading vehicle records…" : <>Showing <b>{total ? offset + 1 : 0}–{Math.min(offset + pageSize, total)}</b> of <b>{total}</b> vehicle records</>}</span><span>Connected to the vehicle API</span></div>{error && <p className="cu-api-error">{error}</p>}
      <section className="cu-table-card"><div className="cu-table-wrap"><table className="vh-table"><thead><tr><th className="cu-sticky-action">Actions</th><th>Vehicle ID</th><th>Plate Number</th><th>Fleet No.</th><th>Make &amp; Model</th><th>Year</th><th>Registration Expiry</th><th>Insurance Expiry</th><th>Latest KM</th><th>Tariff Group</th><th>Status</th></tr></thead><tbody>{records.map((vehicle) => <tr key={vehicle.VehicleId}><td className="cu-sticky-action"><div className="cu-actions"><button aria-label="View vehicle" onClick={() => { setSelected(vehicle); setDrawer("view"); }} type="button"><Icon name="visibility" /></button><button aria-label="Edit vehicle" onClick={() => { setSelected(vehicle); setDrawer("edit"); }} type="button"><Icon name="edit" /></button><button aria-label="Vehicle deletion is disabled" disabled type="button"><Icon name="delete" /></button></div></td><td><code>VEH-{vehicle.VehicleId}</code></td><td><span className="vh-plate">{vehicle.PlateNo}</span></td><td><code>{vehicle.VHType || "—"}</code></td><td><b>{label(lookups.models, vehicle.ModelId)}</b><small>{label(lookups.makes, lookups.models?.find((item) => item.id === vehicle.ModelId)?.parentId)}</small></td><td>{vehicle.Year}</td><td>{dateDisplay(vehicle.RegistrationExpiryDate)}</td><td>{dateDisplay(vehicle.InsuranceExpDate)}</td><td><code>{vehicle.LatestKmRdg.toLocaleString()}</code></td><td>{label(lookups.tariffGroups, vehicle.TariffGroupId)}</td><td><span className="cu-type corporate"><i />{label(lookups.statuses, vehicle.StatusId)}</span></td></tr>)}</tbody></table></div><footer className="cu-pagination"><span>Page {currentPage} of {totalPages}</span><div><button disabled={offset === 0 || loading} onClick={() => loadPage(Math.max(0, offset - pageSize))} type="button">Previous</button>{pageNumbers.map((page) => <button key={page} className={page === currentPage ? "cu-page-active" : ""} disabled={loading || page === currentPage} onClick={() => loadPage((page - 1) * pageSize)} type="button">{page}</button>)}<button disabled={offset + pageSize >= total || loading} onClick={() => loadPage(offset + pageSize)} type="button">Next</button></div></footer></section>
    </main></div>{drawer && <VehicleDrawer lookups={lookups} mode={drawer} user={user} vehicle={selected} onClose={() => setDrawer(null)} onEdit={() => setDrawer("edit")} onSaved={() => { setDrawer(null); void loadPage(offset); }} />}</div>;
}

async function loadLookups(setLookups: (value: Lookups) => void) {
  const specs: [string, string, string, string[]][] = [["states", "states", "StateId", ["StateName"]], ["makes", "makes", "MakeId", ["MakeName"]], ["vehicle-types", "types", "TypeId", ["TypeName"]], ["fuel-types", "fuelTypes", "FuelTypeId", ["FuelTypeName"]], ["fuel-capacity-units", "fuelUnits", "FuelCapUnitId", ["FuelCapUnit"]], ["transmission-types", "transmissions", "TransmissionId", ["TransmissionName"]], ["colours", "colours", "ColourId", ["ColourName"]], ["insurance-policies", "policies", "InsurancePolicyId", ["InsurancePolicyNo"]], ["insurance-companies", "companies", "InsuranceCompanyId", ["InsuranceCompanyName"]], ["insurance-types", "insuranceTypes", "InsuranceTypeId", ["InsuranceTypeName"]], ["tc-nos", "tcNos", "TCNoId", ["TCNo"]], ["tariff-groups", "tariffGroups", "TariffGroupId", ["TariffGroupName"]], ["company-branches", "branches", "BranchId", ["BranchName"]], ["locations", "locations", "LocationId", ["LocationName"]], ["statuses", "statuses", "StatusId", ["StatusName"]], ["fuel-levels", "fuelLevels", "FuelLevelId", ["FuelLevel"]]];
  const values = await Promise.all(specs.map(async ([path, key, idKey, labelKeys]) => [key, optionRows(await getLookup(path), idKey, labelKeys)] as const)); const result = Object.fromEntries(values) as Lookups;
  const categories = (await Promise.all((result.states ?? []).map(async (state) => optionRows(await getLookup(`plate-categories?state_id=${state.id}`), "PlateCategoryId", ["PlateCategoryName"], "StateId")))).flat(); result.categories = categories;
  result.plateCodes = (await Promise.all(categories.map(async (category) => optionRows(await getLookup(`plate-codes?plate_category_id=${category.id}`), "PlateCodeId", ["PlateCodeName", "Code"], "PlateCategoryId")))).flat();
  const models = (await Promise.all((result.makes ?? []).map(async (make) => optionRows(await getLookup(`models?make_id=${make.id}`), "ModelId", ["ModelName"], "MakeId")))).flat(); result.models = models;
  result.capacities = (await Promise.all(models.map(async (model) => optionRows(await getLookup(`engine-capacities?model_id=${model.id}`), "EngineCapacityId", ["EngineCapacity"], "ModelId")))).flat(); setLookups(result);
}

function VehicleDrawer({ vehicle, mode, user, lookups, onClose, onEdit, onSaved }: { vehicle: VehicleRecord | null; mode: "create" | "view" | "edit"; user: AuthenticatedUser; lookups: Lookups; onClose: () => void; onEdit: () => void; onSaved: () => void }) {
  const editable = mode !== "view"; const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null); const title = mode === "create" ? "Add Vehicle" : mode === "edit" ? "Edit Vehicle" : "Vehicle Details";
  async function submit(form: HTMLFormElement) { const values = new FormData(form); const required = ["ModelId", "EngineCapacityId", "Year", "PlateCodeId", "PlateNo", "RegistrationStartDate", "RegistrationExpiryDate", "InsurancePolicyId", "InsuranceExpDate", "InsuranceCompanyId", "InsuranceTypeId", "TCNoId", "TypeId", "FuelCapacity", "FuelCapacityUnitId", "ChasisNo", "EngineNo", "TransmissionId", "FuelTypeId", "ColourId", "SalikTag", "InitialKmRdg", "TariffGroupId", "StatusId"]; const missing = required.find((name) => !String(values.get(name) ?? "").trim()); if (missing) { setError(`${fieldName(missing)} is required.`); return; }
    const payload: VehiclePayload = { ModelId: num(values, "ModelId"), EngineCapacityId: num(values, "EngineCapacityId"), Year: num(values, "Year"), PlateCodeId: num(values, "PlateCodeId"), PlateNo: String(values.get("PlateNo")).trim(), RegistrationStartDate: toDate(values.get("RegistrationStartDate"))!, RegistrationExpiryDate: toDate(values.get("RegistrationExpiryDate"))!, InsurancePolicyId: num(values, "InsurancePolicyId"), InsurancePolicyRecNo: num(values, "InsurancePolicyRecNo", true) ?? 0, InsuranceExpDate: toDate(values.get("InsuranceExpDate"))!, InsuranceCompanyId: num(values, "InsuranceCompanyId"), InsuranceTypeId: num(values, "InsuranceTypeId"), TCNoId: num(values, "TCNoId"), TypeId: num(values, "TypeId"), FuelCapacity: num(values, "FuelCapacity"), FuelCapacityUnitId: num(values, "FuelCapacityUnitId"), ChasisNo: String(values.get("ChasisNo")).trim(), EngineNo: String(values.get("EngineNo")).trim(), TransmissionId: num(values, "TransmissionId"), FuelTypeId: num(values, "FuelTypeId"), ColourId: num(values, "ColourId"), SalikTag: String(values.get("SalikTag")).trim(), InitialKmRdg: num(values, "InitialKmRdg"), LatestKmRdg: num(values, "LatestKmRdg", true), TariffGroupId: num(values, "TariffGroupId"), StatusId: num(values, "StatusId"), Remarks: String(values.get("Remarks") ?? "").trim() || null, NextDueService: num(values, "NextDueService", true), AlertDate: toDate(values.get("AlertDate")), BranchId: num(values, "BranchId", true), LocId: num(values, "LocId", true), FuelLevel: num(values, "FuelLevel", true), VHType: String(values.get("VHType") ?? "").trim() || null };
    setSaving(true); setError(null); try { if (mode === "create") await createVehicle({ ...payload, CreatedBy: user.userId }); else if (vehicle) await updateVehicle(vehicle.VehicleId, { ...payload, LastUpdatedBy: user.userId }); onSaved(); } catch (cause) { setError(cause instanceof Error ? cause.message : "The vehicle could not be saved."); } finally { setSaving(false); }
  }
  return <div className="cu-drawer-backdrop"><aside className="cu-drawer vh-drawer"><header><div><small>{mode === "create" ? "NEW VEHICLE" : "VEHICLE MASTER"}</small><h2>{title} {vehicle && <em>VEH-{vehicle.VehicleId}</em>}</h2></div><button aria-label="Close drawer" onClick={onClose} type="button"><Icon name="close" /></button></header><div className="cu-drawer-content">{error && <p className="cu-api-error">{error}</p>}{editable ? <VehicleForm vehicle={vehicle} lookups={lookups} onSubmit={submit} /> : vehicle && <VehicleView vehicle={vehicle} lookups={lookups} />}</div><footer>{mode === "view" ? <><button onClick={onClose} type="button">Close</button><button className="cu-primary" onClick={onEdit} type="button"><Icon name="edit" />Edit Vehicle</button></> : <><button onClick={onClose} type="button">Cancel</button><button className="cu-primary" form="vehicle-form" disabled={saving} type="submit"><Icon name={mode === "create" ? "person_add" : "save"} />{saving ? "Saving…" : mode === "create" ? "Save Vehicle" : "Update Vehicle"}</button></>}<p>Changes are sent to the FleetTrack vehicle API only when you save.</p></footer></aside></div>;
}

function Select({ name, label: title, options, value, required = false }: { name: string; label: string; options?: Option[]; value?: number | null; required?: boolean }) { return <label>{title}{required && " *"}<select name={name} defaultValue={value ?? ""} required={required}><option value="">Select {title}</option>{options?.map((option) => <option key={option.id} value={option.id}>{option.label}</option>)}</select></label>; }
function Input({ name, label: title, value, type = "text", required = false }: { name: string; label: string; value?: string | number | null; type?: string; required?: boolean }) { return <label>{title}{required && " *"}<input name={name} type={type} defaultValue={value ?? ""} required={required} min={type === "number" ? 0 : undefined} /></label>; }
function VehicleForm({ vehicle, lookups, onSubmit }: { vehicle: VehicleRecord | null; lookups: Lookups; onSubmit: (form: HTMLFormElement) => void }) {
  const initialModelId = vehicle?.ModelId ?? 0;
  const [makeId, setMakeId] = useState(lookups.models?.find((item) => item.id === initialModelId)?.parentId ?? 0);
  const [modelId, setModelId] = useState(initialModelId);
  const [capacityId, setCapacityId] = useState(vehicle?.EngineCapacityId ?? 0);
  const [stateId, setStateId] = useState(0);
  const models = lookups.models?.filter((item) => item.parentId === makeId) ?? [];
  const capacities = lookups.capacities?.filter((item) => item.parentId === modelId) ?? [];
  return <form className="cu-form vh-form" id="vehicle-form" onSubmit={(event) => { event.preventDefault(); onSubmit(event.currentTarget); }}>
    <section><h3>Plate Details</h3><div className="cu-form-grid"><label>State / Emirate<select defaultValue="" onChange={(event) => setStateId(Number(event.target.value))}><option value="">Select State</option>{lookups.states?.map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</select></label><label>Plate Category<select defaultValue=""><option value="">Select Category</option>{lookups.categories?.filter((item) => !stateId || item.parentId === stateId).map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</select></label><Select name="PlateCodeId" label="Plate Code" options={lookups.plateCodes} value={vehicle?.PlateCodeId} required /><Input name="PlateNo" label="Plate Number" value={vehicle?.PlateNo} required /><Input name="VHType" label="Fleet Number" value={vehicle?.VHType} /></div></section>
    <section><h3>Make &amp; Technical Details</h3><div className="cu-form-grid"><label>Make<select value={makeId || ""} onChange={(event) => { setMakeId(Number(event.target.value)); setModelId(0); setCapacityId(0); }}><option value="">Select Make</option>{lookups.makes?.map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</select></label><label>Model *<select name="ModelId" disabled={!makeId} required value={modelId || ""} onChange={(event) => { setModelId(Number(event.target.value)); setCapacityId(0); }}><option value="">{makeId ? "Select Model" : "Select Make first"}</option>{models.map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</select></label><label>Engine Capacity *<select name="EngineCapacityId" disabled={!modelId} required value={capacityId || ""} onChange={(event) => setCapacityId(Number(event.target.value))}><option value="">{modelId ? "Select Engine Capacity" : "Select Model first"}</option>{capacities.map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</select></label><Input name="Year" label="Year of Manufacture" type="number" value={vehicle?.Year} required /><Select name="TypeId" label="Vehicle Type" options={lookups.types} value={vehicle?.TypeId} required /><Select name="FuelTypeId" label="Fuel Type" options={lookups.fuelTypes} value={vehicle?.FuelTypeId} required /><Input name="FuelCapacity" label="Fuel Capacity" type="number" value={vehicle?.FuelCapacity} required /><Select name="FuelCapacityUnitId" label="Fuel Capacity Unit" options={lookups.fuelUnits} value={vehicle?.FuelCapacityUnitId} required /><Input name="EngineNo" label="Engine Number" value={vehicle?.EngineNo} required /><Input name="ChasisNo" label="Chassis Number" value={vehicle?.ChasisNo} required /><Select name="TransmissionId" label="Transmission" options={lookups.transmissions} value={vehicle?.TransmissionId} required /><Select name="ColourId" label="Colour" options={lookups.colours} value={vehicle?.ColourId} required /></div></section>
    <section><h3>Registration &amp; Insurance</h3><div className="cu-form-grid"><Input name="RegistrationStartDate" label="Registration Start" type="date" value={dateInput(vehicle?.RegistrationStartDate)} required /><Input name="RegistrationExpiryDate" label="Registration Expiry" type="date" value={dateInput(vehicle?.RegistrationExpiryDate)} required /><Select name="InsurancePolicyId" label="Insurance Policy" options={lookups.policies} value={vehicle?.InsurancePolicyId} required /><Input name="InsurancePolicyRecNo" label="Policy Record No." type="number" value={vehicle?.InsurancePolicyRecNo ?? 0} /><Select name="InsuranceCompanyId" label="Insurance Company" options={lookups.companies} value={vehicle?.InsuranceCompanyId} required /><Select name="InsuranceTypeId" label="Insurance Type" options={vehicle?.InsuranceTypeId === 3 && !lookups.insuranceTypes?.some((item) => item.id === 3) ? [{ id: 3, label: "Legacy insurance type (ID 3)" }, ...(lookups.insuranceTypes ?? [])] : lookups.insuranceTypes} value={vehicle?.InsuranceTypeId} required /><Input name="InsuranceExpDate" label="Insurance Expiry" type="date" value={dateInput(vehicle?.InsuranceExpDate)} required /></div></section>
    <section><h3>RTA &amp; Operations</h3><div className="cu-form-grid"><Select name="TCNoId" label="TC Number" options={lookups.tcNos} value={vehicle?.TCNoId} required /><Input name="SalikTag" label="Salik Tag" value={vehicle?.SalikTag} required /><Input name="InitialKmRdg" label="Initial KM" type="number" value={vehicle?.InitialKmRdg} required /><Input name="LatestKmRdg" label="Latest KM" type="number" value={vehicle?.LatestKmRdg} /><Select name="TariffGroupId" label="Tariff Group" options={lookups.tariffGroups} value={vehicle?.TariffGroupId} required /><Select name="StatusId" label="Status" options={lookups.statuses} value={vehicle?.StatusId} required /><Select name="BranchId" label="Branch" options={lookups.branches} value={vehicle?.BranchId} /><Select name="LocId" label="Location" options={lookups.locations} value={vehicle?.LocId} /><Select name="FuelLevel" label="Fuel Level" options={lookups.fuelLevels} value={vehicle?.FuelLevel} /><Input name="NextDueService" label="Next Due Service (KM)" type="number" value={vehicle?.NextDueService} /><Input name="AlertDate" label="Alert Date" type="date" value={dateInput(vehicle?.AlertDate)} /><label className="cu-form-full">Remarks<textarea name="Remarks" defaultValue={vehicle?.Remarks ?? ""} /></label></div></section>
  </form>;
}

function VehicleView({ vehicle, lookups }: { vehicle: VehicleRecord; lookups: Lookups }) { const model = label(lookups.models, vehicle.ModelId); const make = label(lookups.makes, lookups.models?.find((item) => item.id === vehicle.ModelId)?.parentId); return <div className="cu-details vh-details"><DetailSection title="Plate Details" items={[["Plate Number", vehicle.PlateNo], ["Fleet Number", vehicle.VHType], ["Plate Code", label(lookups.plateCodes, vehicle.PlateCodeId)]]} /><DetailSection title="Make & Technical Details" items={[["Make", make], ["Model", model], ["Engine Capacity", label(lookups.capacities, vehicle.EngineCapacityId)], ["Year", vehicle.Year], ["Vehicle Type", label(lookups.types, vehicle.TypeId)], ["Fuel", `${label(lookups.fuelTypes, vehicle.FuelTypeId)} · ${vehicle.FuelCapacity} ${label(lookups.fuelUnits, vehicle.FuelCapacityUnitId)}`], ["Engine Number", vehicle.EngineNo], ["Chassis Number", vehicle.ChasisNo], ["Transmission", label(lookups.transmissions, vehicle.TransmissionId)], ["Colour", label(lookups.colours, vehicle.ColourId)]]} /><DetailSection title="Registration & Insurance" items={[["Registration Start", dateDisplay(vehicle.RegistrationStartDate)], ["Registration Expiry", dateDisplay(vehicle.RegistrationExpiryDate)], ["Insurance Policy", label(lookups.policies, vehicle.InsurancePolicyId)], ["Insurance Company", label(lookups.companies, vehicle.InsuranceCompanyId)], ["Insurance Type", vehicle.InsuranceTypeId === 3 ? "Legacy insurance type (ID 3)" : label(lookups.insuranceTypes, vehicle.InsuranceTypeId)], ["Insurance Expiry", dateDisplay(vehicle.InsuranceExpDate)]]} /><DetailSection title="RTA & Operations" items={[["TC Number", label(lookups.tcNos, vehicle.TCNoId)], ["Salik Tag", vehicle.SalikTag], ["Initial / Latest KM", `${vehicle.InitialKmRdg.toLocaleString()} / ${vehicle.LatestKmRdg.toLocaleString()}`], ["Tariff Group", label(lookups.tariffGroups, vehicle.TariffGroupId)], ["Status", label(lookups.statuses, vehicle.StatusId)], ["Branch", label(lookups.branches, vehicle.BranchId)], ["Location", label(lookups.locations, vehicle.LocId)], ["Next Due Service", vehicle.NextDueService?.toLocaleString() ?? "—"], ["Alert Date", dateDisplay(vehicle.AlertDate)], ["Remarks", vehicle.Remarks || "—"]]} /></div>; }
function DetailSection({ title, items }: { title: string; items: [string, string | number | null | undefined][] }) { return <section><h3>{title}</h3><div>{items.map(([name, value]) => <p key={name}><small>{name}</small><b>{value ?? "—"}</b></p>)}</div></section>; }
function fieldName(value: string) { return value.replace(/([A-Z])/g, " $1").trim().replace("Chasis", "Chassis").replace("Km", "KM"); }
