"use client";

import { useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { createContract, getCurrentUser, getLookup, getVehiclesPage, logout, type AuthenticatedUser, type ContractPayload, type LookupRecord, type VehicleRecord } from "@/lib/api";
import { FleetSidebar } from "@/components/fleet-sidebar";

type Option = { id: string | number; label: string; data: LookupRecord };
type Lookups = Record<string, Option[]>;
type Summary = { type: string; days: number; rate: number; insurance: number; advance: number; subtotal: number };

const lookupSpecs: [string, string, string, string[]][] = [
  ["contract-types", "contractTypes", "contractType", ["contractTypeName", "contractType"]], ["locations", "locations", "LocationId", ["LocationName"]],
  ["sales-persons", "salespeople", "employeeId", ["employeeName", "employeeCode"]], ["billing-types", "billingTypes", "invoiceTypeId", ["invoiceTypeName", "InvoiceType"]],
  ["visa-types", "visaTypes", "Id", ["VisaType"]], ["license-types", "licenseTypes", "DLTypeId", ["DLTypeName"]], ["nationalities", "nationalities", "NationalityId", ["NationalityName"]],
  ["fuel-levels", "fuelLevels", "FuelLevelId", ["FuelLevel"]], ["application-users", "appUsers", "UserID", ["DisplayName", "UserName"]],
  ["payment-modes", "paymentModes", "paymentMode", ["paymentModeName", "PaymentMode"]], ["discount-types", "discountTypes", "DiscountTypeId", ["DiscountTypeName"]], ["customers", "customers", "ledgerId", ["ledgerName"]],
];
const charges: [string, string][] = [["Rate", "Base Rate"], ["CDW", "CDW Insurance"], ["PAI", "PAI Insurance"], ["DriverCharges", "Driver Charges"], ["AddDriverCharges", "Additional Driver"], ["ExcessKmCharge", "Excess KM Rate"], ["FuelCharges", "Fuel Charges"], ["SalikCharges", "Salik Tolls"], ["ExcessInsCharges", "Excess Insurance"], ["TrafficCharges", "Traffic Fines"], ["MileageCap", "Daily KM Cap"], ["OtherCharges", "Other Charges"]];
const now = () => new Date().toISOString().slice(0, 16);
const options = (rows: LookupRecord[], idKey: string, labels: string[]): Option[] => rows.map((data) => { const id = data[idKey]; const label = labels.map((key) => data[key]).find((value) => value !== null && value !== undefined); return { id: typeof id === "number" || typeof id === "string" ? id : "", label: String(label ?? id ?? "—"), data }; }).filter((item) => item.id !== "");

function Field({ label, name, type = "text", value, required = false }: { label: string; name: string; type?: string; value?: string | number; required?: boolean }) {
  return <label>{label}{required && <em>*</em>}<input defaultValue={value ?? ""} name={name} required={required} step={type === "number" ? "any" : undefined} type={type} /></label>;
}
function Choice({ label, name, rows, value, required = false, disabled = false, onChange }: { label: string; name: string; rows?: Option[]; value?: string | number; required?: boolean; disabled?: boolean; onChange?: (event: React.ChangeEvent<HTMLSelectElement>) => void }) {
  return <label>{label}{required && <em>*</em>}<select defaultValue={value ?? ""} disabled={disabled} key={`${name}-${rows?.length ?? 0}-${value ?? ""}`} name={name} onChange={onChange} required={required}><option value="">{disabled ? "Select customer first" : `Select ${label}`}</option>{rows?.map((row, index) => <option key={`${row.id}-${index}`} value={String(row.id)}>{row.label}</option>)}</select></label>;
}
function Panel({ number, title, children, className = "" }: { number: number; title: string; children: React.ReactNode; className?: string }) { return <section className={`ca-panel ${className}`}><header><span>{number}</span><h2>{title}</h2></header>{children}</section>; }

export default function AddContractPage() {
  const router = useRouter(); const formRef = useRef<HTMLFormElement>(null);
  const [user, setUser] = useState<AuthenticatedUser | null>(null); const [lookups, setLookups] = useState<Lookups>({}); const [vehicles, setVehicles] = useState<VehicleRecord[]>([]);
  const [customer, setCustomer] = useState<Option | null>(null); const [customerUsers, setCustomerUsers] = useState<Option[]>([]); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null);
  const [summary, setSummary] = useState<Summary>({ type: "Not selected", days: 0, rate: 0, insurance: 0, advance: 0, subtotal: 0 });

  useEffect(() => { async function load() { try { const active = await getCurrentUser(); setUser(active); const entries = await Promise.all(lookupSpecs.map(async ([path, key, id, labels]) => [key, options(await getLookup(path), id, labels)] as const)); setLookups(Object.fromEntries(entries)); const first = await getVehiclesPage(0, 100); const second = first.total > 100 ? await getVehiclesPage(100, 100) : { items: [] as VehicleRecord[] }; setVehicles([...first.items, ...second.items]); } catch (cause) { if (cause instanceof Error && cause.message.includes("session")) router.replace("/login"); else setError(cause instanceof Error ? cause.message : "Contract form could not be loaded."); } } void load(); }, [router]);

  function refreshSummary(form: HTMLFormElement) { const data = new FormData(form); const amount = (name: string) => Number(data.get(name) || 0); const start = new Date(String(data.get("ContractStartDate") || "")); const end = new Date(String(data.get("ContractExpectedEndDate") || "")); const days = Number.isFinite(start.getTime()) && Number.isFinite(end.getTime()) ? Math.max(0, Math.ceil((end.getTime() - start.getTime()) / 86400000)) : 0; const typeId = String(data.get("ContractType") || ""); const type = lookups.contractTypes?.find((item) => String(item.id) === typeId)?.label ?? "Not selected"; const gross = charges.reduce((total, [name]) => name === "MileageCap" ? total : total + amount(name), 0); const subtotal = Math.max(0, gross - amount("Discount")); setSummary({ type, days, rate: amount("Rate"), insurance: amount("CDW") + amount("PAI"), advance: amount("Advance"), subtotal }); }
  async function customerChanged(event: React.ChangeEvent<HTMLSelectElement>) { const id = Number(event.target.value); setCustomer(lookups.customers?.find((item) => Number(item.id) === id) ?? null); setCustomerUsers([]); if (!id) return; try { setCustomerUsers(options(await getLookup(`customer-users?customer_id=${id}`), "ContractDriverId", ["UserName"])); } catch (cause) { setError(cause instanceof Error ? cause.message : "Prior drivers could not be loaded."); } }
  function driverChanged(event: React.ChangeEvent<HTMLSelectElement>) { const row = customerUsers.find((item) => String(item.id) === event.target.value); const form = formRef.current; if (!row || !form) return; const set = (name: string, value: unknown) => { const node = form.elements.namedItem(name) as HTMLInputElement | HTMLSelectElement | null; if (node && value != null) node.value = String(value).slice(0, 10); }; set("UserName", row.data.UserName); set("DateOfBirth", row.data.DateOfBirth); set("Nationality", row.data.NationalityId); set("VisaType", row.data.VisaType); set("VisaExpiryDate", row.data.VisaExpiryDate); set("DrivingLicenseType", row.data.DrivingLicenseType); set("DrivingLicenseNo", row.data.DrivingLicenseNo); set("DLPlaceOfIssue", row.data.DLPlaceOfIssue); set("DLIssueDate", row.data.DLIssueDate); set("DLExpiryDate", row.data.DLExpiryDate); }

  async function submit(form: HTMLFormElement) { if (!user) return; const data = new FormData(form); const required = ["ContractRefNo", "ContractType", "ContractLocId", "ContractStartDate", "ContractExpectedEndDate", "CustomerId", "UserName", "DateOfBirth", "Nationality", "VisaType", "VisaExpiryDate", "DrivingLicenseType", "DrivingLicenseNo", "DLPlaceOfIssue", "DLIssueDate", "DLExpiryDate", "VehicleId"]; const missing = required.find((name) => !String(data.get(name) ?? "").trim()); if (missing) { setError(`${missing.replace(/([A-Z])/g, " $1").trim()} is required.`); return; } const number = (name: string, fallback = 0) => Number(data.get(name) || fallback); const text = (name: string) => String(data.get(name) ?? "").trim(); const payload: ContractPayload = { ContractRefNo: number("ContractRefNo"), ContractType: number("ContractType"), ContractStartDate: text("ContractStartDate"), ContractExpectedEndDate: text("ContractExpectedEndDate"), ContractLocId: number("ContractLocId"), CustomerId: number("CustomerId"), UserName: text("UserName"), VehicleId: number("VehicleId"), DateOfBirth: text("DateOfBirth"), Nationality: text("Nationality"), VisaType: number("VisaType"), VisaExpiryDate: text("VisaExpiryDate"), DrivingLicenseType: number("DrivingLicenseType"), DrivingLicenseNo: text("DrivingLicenseNo"), DLPlaceOfIssue: text("DLPlaceOfIssue"), DLIssueDate: text("DLIssueDate"), DLExpiryDate: text("DLExpiryDate"), PaymentMode: number("PaymentMode", 1), DiscountType: number("DiscountType", 1), BillingType: number("BillingType", 2), DatetimeOut: text("DatetimeOut") || null, KmOut: text("KmOut") ? number("KmOut") : null, FuelLevelIdOut: number("FuelLevelIdOut", 1), CheckedOutBy: number("CheckedOutBy") || null, LocationOut: number("LocationOut") || null, SalesPersonId: number("SalesPersonId") || null, Discount: number("Discount"), Advance: number("Advance"), Subtotal: summary.subtotal, ConfirmationRefValue: text("ConfirmationRefValue") || null, Remarks: text("Remarks") || null, CreatedBy: user.userId, IsAdvanceInvoice: data.get("IsAdvanceInvoice") === "on" }; for (const [name] of charges) payload[name] = number(name); setSaving(true); setError(null); try { await createContract(payload); router.push("/contracts/list"); } catch (cause) { setError(cause instanceof Error ? cause.message : "Contract could not be saved."); } finally { setSaving(false); } }

  if (!user) return <main className="ft-loading">Loading FleetTrack contract form…</main>;
  const vehicleRows: Option[] = vehicles.map((vehicle) => ({ id: vehicle.VehicleId, label: `${vehicle.PlateNo} · FLT-${vehicle.VHType || vehicle.VehicleId} · ${vehicle.Year} · ${vehicle.LatestKmRdg.toLocaleString()} KM`, data: vehicle as unknown as LookupRecord }));
  const currency = (value: number) => value.toLocaleString("en-AE", { minimumFractionDigits: 2, maximumFractionDigits: 2 });

  return <div className="cu-app"><FleetSidebar /><div className="cu-frame"><header className="cu-topbar"><div className="cu-crumb"><b>FleetTrack</b><span>/</span><span>Operations</span><span>/</span><strong>Add Contract</strong></div><div className="cu-user"><span className="cu-avatar">{user.displayName.slice(0, 2).toUpperCase()}</span><span><b>{user.displayName}</b><small>{user.userName}</small></span><button className="cu-logout" onClick={() => { void logout().finally(() => router.replace("/login")); }} type="button">Logout</button></div></header><main className="cu-main ca-main"><div className="cu-page-heading"><div><h1>Add Contract</h1><p>Create a rental agreement, primary-driver record, and vehicle assignment.</p></div></div>{error && <p className="cu-api-error">{error}</p>}
    <form className="ca-form" ref={formRef} onInput={(event) => refreshSummary(event.currentTarget)} onSubmit={(event) => { event.preventDefault(); void submit(event.currentTarget); }}>
      <div className="ca-left"><Panel number={1} title="Agreement & Customer"><div className="ca-grid ca-three"><Field label="Agreement No" name="ContractRefNo" required type="number" /><Choice label="Type" name="ContractType" required rows={lookups.contractTypes} /><Choice label="Location" name="ContractLocId" required rows={lookups.locations} /><Field label="Start Date/Time" name="ContractStartDate" required type="datetime-local" value={now()} /><Field label="End Date/Time" name="ContractExpectedEndDate" required type="datetime-local" value={now()} /><Choice label="Billing Cycle" name="BillingType" rows={lookups.billingTypes} value={2} /><Choice label="Sales Person" name="SalesPersonId" rows={lookups.salespeople} /><label className="ca-check"><input defaultChecked name="IsAdvanceInvoice" type="checkbox" />Advance Invoice Required</label></div><div className="ca-customer"><Choice label="Registered Customer" name="CustomerId" onChange={customerChanged} required rows={lookups.customers} />{customer && <div><b>{customer.label}</b><span>{String(customer.data.mobile || customer.data.phone || "Not recorded")}</span><span>{String(customer.data.email || "Not recorded")}</span></div>}</div></Panel>
        <Panel number={2} title="Primary Driver & Licence"><div className="ca-grid ca-three"><Choice disabled={!customer} label="Prior Customer User (Optional)" name="CustomerUser" onChange={driverChanged} rows={customerUsers} /><Field label="Driver Name" name="UserName" required /><Field label="Date of Birth" name="DateOfBirth" required type="date" /><Choice label="Nationality" name="Nationality" required rows={lookups.nationalities} /><Choice label="Visa Type" name="VisaType" required rows={lookups.visaTypes} /><Field label="Visa Expiry" name="VisaExpiryDate" required type="date" /><Choice label="Licence Type" name="DrivingLicenseType" required rows={lookups.licenseTypes} /><Field label="Licence No" name="DrivingLicenseNo" required /><Field label="Issue Date" name="DLIssueDate" required type="date" /><Field label="Expiry Date" name="DLExpiryDate" required type="date" /><div className="ca-span-three"><Field label="Place of Issue" name="DLPlaceOfIssue" required /></div></div></Panel></div>
      <div className="ca-middle"><Panel number={3} title="Vehicle & Handover"><div className="ca-grid ca-two"><div className="ca-span-two"><Choice label="Fleet Asset" name="VehicleId" required rows={vehicleRows} /></div><Field label="Date/Time Out" name="DatetimeOut" type="datetime-local" value={now()} /><Field label="Odometer Out (KM)" name="KmOut" type="number" /><Choice label="Fuel Level" name="FuelLevelIdOut" rows={lookups.fuelLevels} value={1} /><Choice label="Checked Out By" name="CheckedOutBy" rows={lookups.appUsers} value={user.userId} /><div className="ca-span-two"><Choice label="Handover Location" name="LocationOut" rows={lookups.locations} /></div></div></Panel>
        <Panel number={4} title="Rates, Charges & Settlement" className="ca-charges"><div className="ca-charge-grid">{charges.map(([name, label]) => <Field key={name} label={label} name={name} type="number" value="0.00" />)}</div><div className="ca-grid ca-three ca-settlement"><Choice label="Payment Mode" name="PaymentMode" rows={lookups.paymentModes} value={1} /><Field label="Confirmation Ref" name="ConfirmationRefValue" /><Choice label="Discount Type" name="DiscountType" rows={lookups.discountTypes} value={1} /><Field label="Discount" name="Discount" type="number" value="0.00" /><Field label="Advance Received" name="Advance" type="number" value="0.00" /><label className="ca-span-three">Remarks & Special Handling<textarea name="Remarks" /></label></div></Panel></div>
      <aside className="ca-summary"><header><h2>Contract Summary</h2><span>● OPEN</span></header><dl><div><dt>Contract Type</dt><dd>{summary.type}</dd></div><div><dt>Duration</dt><dd>{summary.days} Days</dd></div><div><dt>Base Rate</dt><dd>{currency(summary.rate)} AED/day</dd></div><div><dt>Insurance (CDW+PAI)</dt><dd>{currency(summary.insurance)} AED</dd></div><div><dt>Advance Received</dt><dd>{currency(summary.advance)} AED</dd></div></dl><div className="ca-total"><span>Estimated Daily Total</span><b>{currency(summary.subtotal)} <small>AED</small></b></div><p><b>MVP Notice:</b> Tariffs and charges are entered manually for this operational release.</p><button className="cu-primary" disabled={saving} type="submit">{saving ? "Saving Contract…" : "▣ Save Contract"}</button><div className="ca-secondary"><button onClick={() => router.push("/contracts/list")} type="button">Cancel</button><button onClick={() => { if (window.confirm("Clear all contract fields?")) { formRef.current?.reset(); setCustomer(null); setCustomerUsers([]); setSummary({ type: "Not selected", days: 0, rate: 0, insurance: 0, advance: 0, subtotal: 0 }); } }} type="button">Clear Form</button></div><footer><span>FleetTrack</span><span>{user.displayName}</span></footer></aside>
    </form></main></div></div>;
}
